// Generated by Bisonc++ V4.09.02 on Thu, 23 Nov 2017 22:43:24 +0100

// $insert class.ih
#include "Parser.ih"

// The FIRST element of SR arrays shown below uses `d_type', defining the
// state's type, and `d_lastIdx' containing the last element's index. If
// d_lastIdx contains the REQ_TOKEN bitflag (see below) then the state needs
// a token: if in this state d_token__ is _UNDETERMINED_, nextToken() will be
// called

// The LAST element of SR arrays uses `d_token' containing the last retrieved
// token to speed up the (linear) seach.  Except for the first element of SR
// arrays, the field `d_action' is used to determine what to do next. If
// positive, it represents the next state (used with SHIFT); if zero, it
// indicates `ACCEPT', if negative, -d_action represents the number of the
// rule to reduce to.

// `lookup()' tries to find d_token__ in the current SR array. If it fails, and
// there is no default reduction UNEXPECTED_TOKEN__ is thrown, which is then
// caught by the error-recovery function.

// The error-recovery function will pop elements off the stack until a state
// having bit flag ERR_ITEM is found. This state has a transition on _error_
// which is applied. In this _error_ state, while the current token is not a
// proper continuation, new tokens are obtained by nextToken(). If such a
// token is found, error recovery is successful and the token is
// handled according to the error state's SR table and parsing continues.
// During error recovery semantic actions are ignored.

// A state flagged with the DEF_RED flag will perform a default
// reduction if no other continuations are available for the current token.

// The ACCEPT STATE never shows a default reduction: when it is reached the
// parser returns ACCEPT(). During the grammar
// analysis phase a default reduction may have been defined, but it is
// removed during the state-definition phase.

// So:
//      s_x[] = 
//      {
//                  [_field_1_]         [_field_2_]
//
// First element:   {state-type,        idx of last element},
// Other elements:  {required token,    action to perform},
//                                      ( < 0: reduce, 
//                                          0: ACCEPT,
//                                        > 0: next state)
// Last element:    {set to d_token__,    action to perform}
//      }

// When the --thread-safe option is specified, all static data are defined as
// const. If --thread-safe is not provided, the state-tables are not defined
// as const, since the lookup() function below will modify them


namespace // anonymous
{
    char const author[] = "Frank B. Brokken (f.b.brokken@rug.nl)";

    enum 
    {
        STACK_EXPANSION = 5     // size to expand the state-stack with when
                                // full
    };

    enum ReservedTokens
    {
        PARSE_ACCEPT     = 0,   // `ACCEPT' TRANSITION
        _UNDETERMINED_   = -2,
        _EOF_            = -1,
        _error_          = 256
    };
    enum StateType       // modify statetype/data.cc when this enum changes
    {
        NORMAL,
        ERR_ITEM,
        REQ_TOKEN,
        ERR_REQ,    // ERR_ITEM | REQ_TOKEN
        DEF_RED,    // state having default reduction
        ERR_DEF,    // ERR_ITEM | DEF_RED
        REQ_DEF,    // REQ_TOKEN | DEF_RED
        ERR_REQ_DEF // ERR_ITEM | REQ_TOKEN | DEF_RED
    };    
    struct PI__     // Production Info
    {
        size_t d_nonTerm; // identification number of this production's
                            // non-terminal 
        size_t d_size;    // number of elements in this production 
    };

    struct SR__     // Shift Reduce info, see its description above
    {
        union
        {
            int _field_1_;      // initializer, allowing initializations 
                                // of the SR s_[] arrays
            int d_type;
            int d_token;
        };
        union
        {
            int _field_2_;

            int d_lastIdx;          // if negative, the state uses SHIFT
            int d_action;           // may be negative (reduce), 
                                    // postive (shift), or 0 (accept)
            size_t d_errorState;    // used with Error states
        };
    };

    // $insert staticdata
    
// Productions Info Records:
PI__ const s_productionInfo[] = 
{
     {0, 0}, // not used: reduction values are negative
     {292, 4}, // 1: start ->  kezdes deklaraciok utasitasok befejezes
     {293, 2}, // 2: kezdes (PROGRAM) ->  PROGRAM AZONOSITO
     {296, 1}, // 3: befejezes (PROGRAM_VEGE) ->  PROGRAM_VEGE
     {294, 0}, // 4: deklaraciok ->  <empty>
     {294, 2}, // 5: deklaraciok (VALTOZOK) ->  VALTOZOK valtozolista
     {297, 1}, // 6: valtozolista ->  deklaracio
     {297, 2}, // 7: valtozolista ->  deklaracio valtozolista
     {298, 2}, // 8: deklaracio (EGESZ) ->  EGESZ AZONOSITO
     {298, 2}, // 9: deklaracio (LOGIKAI) ->  LOGIKAI AZONOSITO
     {295, 3}, // 10: utasitasok (UTASITASOK) ->  UTASITASOK utasitas utasitaslista
     {300, 0}, // 11: utasitaslista ->  <empty>
     {300, 2}, // 12: utasitaslista ->  utasitas utasitaslista
     {299, 1}, // 13: utasitas (SKIP) ->  SKIP
     {299, 1}, // 14: utasitas ->  ertekadas
     {299, 1}, // 15: utasitas ->  be
     {299, 1}, // 16: utasitas ->  ki
     {299, 1}, // 17: utasitas ->  elagazas
     {299, 1}, // 18: utasitas ->  ciklus
     {301, 3}, // 19: ertekadas (AZONOSITO) ->  AZONOSITO ERTEKADAS kifejezes
     {302, 2}, // 20: be (BE) ->  BE AZONOSITO
     {303, 2}, // 21: ki (KI) ->  KI kifejezes
     {304, 5}, // 22: elagazas (HA) ->  HA kifejezes AKKOR utasitaslista HA_VEGE
     {304, 7}, // 23: elagazas (HA) ->  HA kifejezes AKKOR utasitaslista KULONBEN utasitaslista HA_VEGE
     {305, 5}, // 24: ciklus (CIKLUS) ->  CIKLUS AMIG kifejezes utasitaslista CIKLUS_VEGE
     {306, 1}, // 25: kifejezes (SZAMKONSTANS) ->  SZAMKONSTANS
     {306, 1}, // 26: kifejezes (IGAZ) ->  IGAZ
     {306, 1}, // 27: kifejezes (HAMIS) ->  HAMIS
     {306, 1}, // 28: kifejezes (AZONOSITO) ->  AZONOSITO
     {306, 3}, // 29: kifejezes (PLUSZ) ->  kifejezes PLUSZ kifejezes
     {306, 3}, // 30: kifejezes (MINUSZ) ->  kifejezes MINUSZ kifejezes
     {306, 3}, // 31: kifejezes (SZORZAS) ->  kifejezes SZORZAS kifejezes
     {306, 3}, // 32: kifejezes (OSZTAS) ->  kifejezes OSZTAS kifejezes
     {306, 3}, // 33: kifejezes (MARADEK) ->  kifejezes MARADEK kifejezes
     {306, 3}, // 34: kifejezes (KISEBB) ->  kifejezes KISEBB kifejezes
     {306, 3}, // 35: kifejezes (NAGYOBB) ->  kifejezes NAGYOBB kifejezes
     {306, 3}, // 36: kifejezes (EGYENLO) ->  kifejezes EGYENLO kifejezes
     {306, 3}, // 37: kifejezes (ES) ->  kifejezes ES kifejezes
     {306, 3}, // 38: kifejezes (VAGY) ->  kifejezes VAGY kifejezes
     {306, 2}, // 39: kifejezes (NEM) ->  NEM kifejezes
     {306, 3}, // 40: kifejezes (BALZAROJEL) ->  BALZAROJEL kifejezes JOBBZAROJEL
     {307, 1}, // 41: start_$ ->  start
};

// State info and SR__ transitions for each state.


SR__ s_0[] =
{
    { { REQ_TOKEN}, { 4} },           
    { {       292}, { 1} }, // start  
    { {       293}, { 2} }, // kezdes 
    { {       258}, { 3} }, // PROGRAM
    { {         0}, { 0} },           
};

SR__ s_1[] =
{
    { { REQ_TOKEN}, {            2} }, 
    { {     _EOF_}, { PARSE_ACCEPT} }, 
    { {         0}, {            0} }, 
};

SR__ s_2[] =
{
    { { REQ_DEF}, {  3} },               
    { {     294}, {  4} }, // deklaraciok
    { {     259}, {  5} }, // VALTOZOK   
    { {       0}, { -4} },               
};

SR__ s_3[] =
{
    { { REQ_TOKEN}, { 2} },             
    { {       276}, { 6} }, // AZONOSITO
    { {         0}, { 0} },             
};

SR__ s_4[] =
{
    { { REQ_TOKEN}, { 3} },              
    { {       295}, { 7} }, // utasitasok
    { {       260}, { 8} }, // UTASITASOK
    { {         0}, { 0} },              
};

SR__ s_5[] =
{
    { { REQ_TOKEN}, {  5} },                
    { {       297}, {  9} }, // valtozolista
    { {       298}, { 10} }, // deklaracio  
    { {       271}, { 11} }, // EGESZ       
    { {       272}, { 12} }, // LOGIKAI     
    { {         0}, {  0} },                
};

SR__ s_6[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -2} }, 
};

SR__ s_7[] =
{
    { { REQ_TOKEN}, {  3} },                
    { {       296}, { 13} }, // befejezes   
    { {       261}, { 14} }, // PROGRAM_VEGE
    { {         0}, {  0} },                
};

SR__ s_8[] =
{
    { { REQ_TOKEN}, { 13} },             
    { {       299}, { 15} }, // utasitas 
    { {       279}, { 16} }, // SKIP     
    { {       301}, { 17} }, // ertekadas
    { {       302}, { 18} }, // be       
    { {       303}, { 19} }, // ki       
    { {       304}, { 20} }, // elagazas 
    { {       305}, { 21} }, // ciklus   
    { {       276}, { 22} }, // AZONOSITO
    { {       269}, { 23} }, // BE       
    { {       270}, { 24} }, // KI       
    { {       262}, { 25} }, // HA       
    { {       266}, { 26} }, // CIKLUS   
    { {         0}, {  0} },             
};

SR__ s_9[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -5} }, 
};

SR__ s_10[] =
{
    { { REQ_DEF}, {  5} },                
    { {     297}, { 27} }, // valtozolista
    { {     298}, { 10} }, // deklaracio  
    { {     271}, { 11} }, // EGESZ       
    { {     272}, { 12} }, // LOGIKAI     
    { {       0}, { -6} },                
};

SR__ s_11[] =
{
    { { REQ_TOKEN}, {  2} },             
    { {       276}, { 28} }, // AZONOSITO
    { {         0}, {  0} },             
};

SR__ s_12[] =
{
    { { REQ_TOKEN}, {  2} },             
    { {       276}, { 29} }, // AZONOSITO
    { {         0}, {  0} },             
};

SR__ s_13[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -1} }, 
};

SR__ s_14[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -3} }, 
};

SR__ s_15[] =
{
    { { REQ_DEF}, {  14} },                 
    { {     300}, {  30} }, // utasitaslista
    { {     299}, {  31} }, // utasitas     
    { {     279}, {  16} }, // SKIP         
    { {     301}, {  17} }, // ertekadas    
    { {     302}, {  18} }, // be           
    { {     303}, {  19} }, // ki           
    { {     304}, {  20} }, // elagazas     
    { {     305}, {  21} }, // ciklus       
    { {     276}, {  22} }, // AZONOSITO    
    { {     269}, {  23} }, // BE           
    { {     270}, {  24} }, // KI           
    { {     262}, {  25} }, // HA           
    { {     266}, {  26} }, // CIKLUS       
    { {       0}, { -11} },                 
};

SR__ s_16[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -13} }, 
};

SR__ s_17[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -14} }, 
};

SR__ s_18[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -15} }, 
};

SR__ s_19[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -16} }, 
};

SR__ s_20[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -17} }, 
};

SR__ s_21[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -18} }, 
};

SR__ s_22[] =
{
    { { REQ_TOKEN}, {  2} },             
    { {       273}, { 32} }, // ERTEKADAS
    { {         0}, {  0} },             
};

SR__ s_23[] =
{
    { { REQ_TOKEN}, {  2} },             
    { {       276}, { 33} }, // AZONOSITO
    { {         0}, {  0} },             
};

SR__ s_24[] =
{
    { { REQ_TOKEN}, {  8} },                
    { {       306}, { 34} }, // kifejezes   
    { {       257}, { 35} }, // SZAMKONSTANS
    { {       277}, { 36} }, // IGAZ        
    { {       278}, { 37} }, // HAMIS       
    { {       276}, { 38} }, // AZONOSITO   
    { {       282}, { 39} }, // NEM         
    { {       274}, { 40} }, // BALZAROJEL  
    { {         0}, {  0} },                
};

SR__ s_25[] =
{
    { { REQ_TOKEN}, {  8} },                
    { {       306}, { 41} }, // kifejezes   
    { {       257}, { 35} }, // SZAMKONSTANS
    { {       277}, { 36} }, // IGAZ        
    { {       278}, { 37} }, // HAMIS       
    { {       276}, { 38} }, // AZONOSITO   
    { {       282}, { 39} }, // NEM         
    { {       274}, { 40} }, // BALZAROJEL  
    { {         0}, {  0} },                
};

SR__ s_26[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       267}, { 42} }, // AMIG
    { {         0}, {  0} },        
};

SR__ s_27[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -7} }, 
};

SR__ s_28[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -8} }, 
};

SR__ s_29[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -9} }, 
};

SR__ s_30[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -10} }, 
};

SR__ s_31[] =
{
    { { REQ_DEF}, {  14} },                 
    { {     300}, {  43} }, // utasitaslista
    { {     299}, {  31} }, // utasitas     
    { {     279}, {  16} }, // SKIP         
    { {     301}, {  17} }, // ertekadas    
    { {     302}, {  18} }, // be           
    { {     303}, {  19} }, // ki           
    { {     304}, {  20} }, // elagazas     
    { {     305}, {  21} }, // ciklus       
    { {     276}, {  22} }, // AZONOSITO    
    { {     269}, {  23} }, // BE           
    { {     270}, {  24} }, // KI           
    { {     262}, {  25} }, // HA           
    { {     266}, {  26} }, // CIKLUS       
    { {       0}, { -11} },                 
};

SR__ s_32[] =
{
    { { REQ_TOKEN}, {  8} },                
    { {       306}, { 44} }, // kifejezes   
    { {       257}, { 35} }, // SZAMKONSTANS
    { {       277}, { 36} }, // IGAZ        
    { {       278}, { 37} }, // HAMIS       
    { {       276}, { 38} }, // AZONOSITO   
    { {       282}, { 39} }, // NEM         
    { {       274}, { 40} }, // BALZAROJEL  
    { {         0}, {  0} },                
};

SR__ s_33[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -20} }, 
};

SR__ s_34[] =
{
    { { REQ_DEF}, {  11} },           
    { {     286}, {  45} }, // PLUSZ  
    { {     287}, {  46} }, // MINUSZ 
    { {     288}, {  47} }, // SZORZAS
    { {     289}, {  48} }, // OSZTAS 
    { {     290}, {  49} }, // MARADEK
    { {     284}, {  50} }, // KISEBB 
    { {     285}, {  51} }, // NAGYOBB
    { {     283}, {  52} }, // EGYENLO
    { {     281}, {  53} }, // ES     
    { {     280}, {  54} }, // VAGY   
    { {       0}, { -21} },           
};

SR__ s_35[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -25} }, 
};

SR__ s_36[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -26} }, 
};

SR__ s_37[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -27} }, 
};

SR__ s_38[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -28} }, 
};

SR__ s_39[] =
{
    { { REQ_TOKEN}, {  8} },                
    { {       306}, { 55} }, // kifejezes   
    { {       257}, { 35} }, // SZAMKONSTANS
    { {       277}, { 36} }, // IGAZ        
    { {       278}, { 37} }, // HAMIS       
    { {       276}, { 38} }, // AZONOSITO   
    { {       282}, { 39} }, // NEM         
    { {       274}, { 40} }, // BALZAROJEL  
    { {         0}, {  0} },                
};

SR__ s_40[] =
{
    { { REQ_TOKEN}, {  8} },                
    { {       306}, { 56} }, // kifejezes   
    { {       257}, { 35} }, // SZAMKONSTANS
    { {       277}, { 36} }, // IGAZ        
    { {       278}, { 37} }, // HAMIS       
    { {       276}, { 38} }, // AZONOSITO   
    { {       282}, { 39} }, // NEM         
    { {       274}, { 40} }, // BALZAROJEL  
    { {         0}, {  0} },                
};

SR__ s_41[] =
{
    { { REQ_TOKEN}, { 12} },           
    { {       263}, { 57} }, // AKKOR  
    { {       286}, { 45} }, // PLUSZ  
    { {       287}, { 46} }, // MINUSZ 
    { {       288}, { 47} }, // SZORZAS
    { {       289}, { 48} }, // OSZTAS 
    { {       290}, { 49} }, // MARADEK
    { {       284}, { 50} }, // KISEBB 
    { {       285}, { 51} }, // NAGYOBB
    { {       283}, { 52} }, // EGYENLO
    { {       281}, { 53} }, // ES     
    { {       280}, { 54} }, // VAGY   
    { {         0}, {  0} },           
};

SR__ s_42[] =
{
    { { REQ_TOKEN}, {  8} },                
    { {       306}, { 58} }, // kifejezes   
    { {       257}, { 35} }, // SZAMKONSTANS
    { {       277}, { 36} }, // IGAZ        
    { {       278}, { 37} }, // HAMIS       
    { {       276}, { 38} }, // AZONOSITO   
    { {       282}, { 39} }, // NEM         
    { {       274}, { 40} }, // BALZAROJEL  
    { {         0}, {  0} },                
};

SR__ s_43[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -12} }, 
};

SR__ s_44[] =
{
    { { REQ_DEF}, {  11} },           
    { {     286}, {  45} }, // PLUSZ  
    { {     287}, {  46} }, // MINUSZ 
    { {     288}, {  47} }, // SZORZAS
    { {     289}, {  48} }, // OSZTAS 
    { {     290}, {  49} }, // MARADEK
    { {     284}, {  50} }, // KISEBB 
    { {     285}, {  51} }, // NAGYOBB
    { {     283}, {  52} }, // EGYENLO
    { {     281}, {  53} }, // ES     
    { {     280}, {  54} }, // VAGY   
    { {       0}, { -19} },           
};

SR__ s_45[] =
{
    { { REQ_TOKEN}, {  8} },                
    { {       306}, { 59} }, // kifejezes   
    { {       257}, { 35} }, // SZAMKONSTANS
    { {       277}, { 36} }, // IGAZ        
    { {       278}, { 37} }, // HAMIS       
    { {       276}, { 38} }, // AZONOSITO   
    { {       282}, { 39} }, // NEM         
    { {       274}, { 40} }, // BALZAROJEL  
    { {         0}, {  0} },                
};

SR__ s_46[] =
{
    { { REQ_TOKEN}, {  8} },                
    { {       306}, { 60} }, // kifejezes   
    { {       257}, { 35} }, // SZAMKONSTANS
    { {       277}, { 36} }, // IGAZ        
    { {       278}, { 37} }, // HAMIS       
    { {       276}, { 38} }, // AZONOSITO   
    { {       282}, { 39} }, // NEM         
    { {       274}, { 40} }, // BALZAROJEL  
    { {         0}, {  0} },                
};

SR__ s_47[] =
{
    { { REQ_TOKEN}, {  8} },                
    { {       306}, { 61} }, // kifejezes   
    { {       257}, { 35} }, // SZAMKONSTANS
    { {       277}, { 36} }, // IGAZ        
    { {       278}, { 37} }, // HAMIS       
    { {       276}, { 38} }, // AZONOSITO   
    { {       282}, { 39} }, // NEM         
    { {       274}, { 40} }, // BALZAROJEL  
    { {         0}, {  0} },                
};

SR__ s_48[] =
{
    { { REQ_TOKEN}, {  8} },                
    { {       306}, { 62} }, // kifejezes   
    { {       257}, { 35} }, // SZAMKONSTANS
    { {       277}, { 36} }, // IGAZ        
    { {       278}, { 37} }, // HAMIS       
    { {       276}, { 38} }, // AZONOSITO   
    { {       282}, { 39} }, // NEM         
    { {       274}, { 40} }, // BALZAROJEL  
    { {         0}, {  0} },                
};

SR__ s_49[] =
{
    { { REQ_TOKEN}, {  8} },                
    { {       306}, { 63} }, // kifejezes   
    { {       257}, { 35} }, // SZAMKONSTANS
    { {       277}, { 36} }, // IGAZ        
    { {       278}, { 37} }, // HAMIS       
    { {       276}, { 38} }, // AZONOSITO   
    { {       282}, { 39} }, // NEM         
    { {       274}, { 40} }, // BALZAROJEL  
    { {         0}, {  0} },                
};

SR__ s_50[] =
{
    { { REQ_TOKEN}, {  8} },                
    { {       306}, { 64} }, // kifejezes   
    { {       257}, { 35} }, // SZAMKONSTANS
    { {       277}, { 36} }, // IGAZ        
    { {       278}, { 37} }, // HAMIS       
    { {       276}, { 38} }, // AZONOSITO   
    { {       282}, { 39} }, // NEM         
    { {       274}, { 40} }, // BALZAROJEL  
    { {         0}, {  0} },                
};

SR__ s_51[] =
{
    { { REQ_TOKEN}, {  8} },                
    { {       306}, { 65} }, // kifejezes   
    { {       257}, { 35} }, // SZAMKONSTANS
    { {       277}, { 36} }, // IGAZ        
    { {       278}, { 37} }, // HAMIS       
    { {       276}, { 38} }, // AZONOSITO   
    { {       282}, { 39} }, // NEM         
    { {       274}, { 40} }, // BALZAROJEL  
    { {         0}, {  0} },                
};

SR__ s_52[] =
{
    { { REQ_TOKEN}, {  8} },                
    { {       306}, { 66} }, // kifejezes   
    { {       257}, { 35} }, // SZAMKONSTANS
    { {       277}, { 36} }, // IGAZ        
    { {       278}, { 37} }, // HAMIS       
    { {       276}, { 38} }, // AZONOSITO   
    { {       282}, { 39} }, // NEM         
    { {       274}, { 40} }, // BALZAROJEL  
    { {         0}, {  0} },                
};

SR__ s_53[] =
{
    { { REQ_TOKEN}, {  8} },                
    { {       306}, { 67} }, // kifejezes   
    { {       257}, { 35} }, // SZAMKONSTANS
    { {       277}, { 36} }, // IGAZ        
    { {       278}, { 37} }, // HAMIS       
    { {       276}, { 38} }, // AZONOSITO   
    { {       282}, { 39} }, // NEM         
    { {       274}, { 40} }, // BALZAROJEL  
    { {         0}, {  0} },                
};

SR__ s_54[] =
{
    { { REQ_TOKEN}, {  8} },                
    { {       306}, { 68} }, // kifejezes   
    { {       257}, { 35} }, // SZAMKONSTANS
    { {       277}, { 36} }, // IGAZ        
    { {       278}, { 37} }, // HAMIS       
    { {       276}, { 38} }, // AZONOSITO   
    { {       282}, { 39} }, // NEM         
    { {       274}, { 40} }, // BALZAROJEL  
    { {         0}, {  0} },                
};

SR__ s_55[] =
{
    { { REQ_DEF}, {   9} },           
    { {     286}, {  45} }, // PLUSZ  
    { {     287}, {  46} }, // MINUSZ 
    { {     288}, {  47} }, // SZORZAS
    { {     289}, {  48} }, // OSZTAS 
    { {     290}, {  49} }, // MARADEK
    { {     284}, {  50} }, // KISEBB 
    { {     285}, {  51} }, // NAGYOBB
    { {     283}, {  52} }, // EGYENLO
    { {       0}, { -39} },           
};

SR__ s_56[] =
{
    { { REQ_TOKEN}, { 12} },               
    { {       275}, { 69} }, // JOBBZAROJEL
    { {       286}, { 45} }, // PLUSZ      
    { {       287}, { 46} }, // MINUSZ     
    { {       288}, { 47} }, // SZORZAS    
    { {       289}, { 48} }, // OSZTAS     
    { {       290}, { 49} }, // MARADEK    
    { {       284}, { 50} }, // KISEBB     
    { {       285}, { 51} }, // NAGYOBB    
    { {       283}, { 52} }, // EGYENLO    
    { {       281}, { 53} }, // ES         
    { {       280}, { 54} }, // VAGY       
    { {         0}, {  0} },               
};

SR__ s_57[] =
{
    { { REQ_DEF}, {  14} },                 
    { {     300}, {  70} }, // utasitaslista
    { {     299}, {  31} }, // utasitas     
    { {     279}, {  16} }, // SKIP         
    { {     301}, {  17} }, // ertekadas    
    { {     302}, {  18} }, // be           
    { {     303}, {  19} }, // ki           
    { {     304}, {  20} }, // elagazas     
    { {     305}, {  21} }, // ciklus       
    { {     276}, {  22} }, // AZONOSITO    
    { {     269}, {  23} }, // BE           
    { {     270}, {  24} }, // KI           
    { {     262}, {  25} }, // HA           
    { {     266}, {  26} }, // CIKLUS       
    { {       0}, { -11} },                 
};

SR__ s_58[] =
{
    { { REQ_DEF}, {  24} },                 
    { {     300}, {  71} }, // utasitaslista
    { {     286}, {  45} }, // PLUSZ        
    { {     287}, {  46} }, // MINUSZ       
    { {     288}, {  47} }, // SZORZAS      
    { {     289}, {  48} }, // OSZTAS       
    { {     290}, {  49} }, // MARADEK      
    { {     284}, {  50} }, // KISEBB       
    { {     285}, {  51} }, // NAGYOBB      
    { {     283}, {  52} }, // EGYENLO      
    { {     281}, {  53} }, // ES           
    { {     280}, {  54} }, // VAGY         
    { {     299}, {  31} }, // utasitas     
    { {     279}, {  16} }, // SKIP         
    { {     301}, {  17} }, // ertekadas    
    { {     302}, {  18} }, // be           
    { {     303}, {  19} }, // ki           
    { {     304}, {  20} }, // elagazas     
    { {     305}, {  21} }, // ciklus       
    { {     276}, {  22} }, // AZONOSITO    
    { {     269}, {  23} }, // BE           
    { {     270}, {  24} }, // KI           
    { {     262}, {  25} }, // HA           
    { {     266}, {  26} }, // CIKLUS       
    { {       0}, { -11} },                 
};

SR__ s_59[] =
{
    { { REQ_DEF}, {   4} },           
    { {     288}, {  47} }, // SZORZAS
    { {     289}, {  48} }, // OSZTAS 
    { {     290}, {  49} }, // MARADEK
    { {       0}, { -29} },           
};

SR__ s_60[] =
{
    { { REQ_DEF}, {   4} },           
    { {     288}, {  47} }, // SZORZAS
    { {     289}, {  48} }, // OSZTAS 
    { {     290}, {  49} }, // MARADEK
    { {       0}, { -30} },           
};

SR__ s_61[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -31} }, 
};

SR__ s_62[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -32} }, 
};

SR__ s_63[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -33} }, 
};

SR__ s_64[] =
{
    { { REQ_DEF}, {   6} },           
    { {     286}, {  45} }, // PLUSZ  
    { {     287}, {  46} }, // MINUSZ 
    { {     288}, {  47} }, // SZORZAS
    { {     289}, {  48} }, // OSZTAS 
    { {     290}, {  49} }, // MARADEK
    { {       0}, { -34} },           
};

SR__ s_65[] =
{
    { { REQ_DEF}, {   6} },           
    { {     286}, {  45} }, // PLUSZ  
    { {     287}, {  46} }, // MINUSZ 
    { {     288}, {  47} }, // SZORZAS
    { {     289}, {  48} }, // OSZTAS 
    { {     290}, {  49} }, // MARADEK
    { {       0}, { -35} },           
};

SR__ s_66[] =
{
    { { REQ_DEF}, {   8} },           
    { {     286}, {  45} }, // PLUSZ  
    { {     287}, {  46} }, // MINUSZ 
    { {     288}, {  47} }, // SZORZAS
    { {     289}, {  48} }, // OSZTAS 
    { {     290}, {  49} }, // MARADEK
    { {     284}, {  50} }, // KISEBB 
    { {     285}, {  51} }, // NAGYOBB
    { {       0}, { -36} },           
};

SR__ s_67[] =
{
    { { REQ_DEF}, {   9} },           
    { {     286}, {  45} }, // PLUSZ  
    { {     287}, {  46} }, // MINUSZ 
    { {     288}, {  47} }, // SZORZAS
    { {     289}, {  48} }, // OSZTAS 
    { {     290}, {  49} }, // MARADEK
    { {     284}, {  50} }, // KISEBB 
    { {     285}, {  51} }, // NAGYOBB
    { {     283}, {  52} }, // EGYENLO
    { {       0}, { -37} },           
};

SR__ s_68[] =
{
    { { REQ_DEF}, {  10} },           
    { {     286}, {  45} }, // PLUSZ  
    { {     287}, {  46} }, // MINUSZ 
    { {     288}, {  47} }, // SZORZAS
    { {     289}, {  48} }, // OSZTAS 
    { {     290}, {  49} }, // MARADEK
    { {     284}, {  50} }, // KISEBB 
    { {     285}, {  51} }, // NAGYOBB
    { {     283}, {  52} }, // EGYENLO
    { {     281}, {  53} }, // ES     
    { {       0}, { -38} },           
};

SR__ s_69[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -40} }, 
};

SR__ s_70[] =
{
    { { REQ_TOKEN}, {  3} },            
    { {       265}, { 72} }, // HA_VEGE 
    { {       264}, { 73} }, // KULONBEN
    { {         0}, {  0} },            
};

SR__ s_71[] =
{
    { { REQ_TOKEN}, {  2} },               
    { {       268}, { 74} }, // CIKLUS_VEGE
    { {         0}, {  0} },               
};

SR__ s_72[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -22} }, 
};

SR__ s_73[] =
{
    { { REQ_DEF}, {  14} },                 
    { {     300}, {  75} }, // utasitaslista
    { {     299}, {  31} }, // utasitas     
    { {     279}, {  16} }, // SKIP         
    { {     301}, {  17} }, // ertekadas    
    { {     302}, {  18} }, // be           
    { {     303}, {  19} }, // ki           
    { {     304}, {  20} }, // elagazas     
    { {     305}, {  21} }, // ciklus       
    { {     276}, {  22} }, // AZONOSITO    
    { {     269}, {  23} }, // BE           
    { {     270}, {  24} }, // KI           
    { {     262}, {  25} }, // HA           
    { {     266}, {  26} }, // CIKLUS       
    { {       0}, { -11} },                 
};

SR__ s_74[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -24} }, 
};

SR__ s_75[] =
{
    { { REQ_TOKEN}, {  2} },           
    { {       265}, { 76} }, // HA_VEGE
    { {         0}, {  0} },           
};

SR__ s_76[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -23} }, 
};


// State array:
SR__ *s_state[] =
{
  s_0,  s_1,  s_2,  s_3,  s_4,  s_5,  s_6,  s_7,  s_8,  s_9,
  s_10,  s_11,  s_12,  s_13,  s_14,  s_15,  s_16,  s_17,  s_18,  s_19,
  s_20,  s_21,  s_22,  s_23,  s_24,  s_25,  s_26,  s_27,  s_28,  s_29,
  s_30,  s_31,  s_32,  s_33,  s_34,  s_35,  s_36,  s_37,  s_38,  s_39,
  s_40,  s_41,  s_42,  s_43,  s_44,  s_45,  s_46,  s_47,  s_48,  s_49,
  s_50,  s_51,  s_52,  s_53,  s_54,  s_55,  s_56,  s_57,  s_58,  s_59,
  s_60,  s_61,  s_62,  s_63,  s_64,  s_65,  s_66,  s_67,  s_68,  s_69,
  s_70,  s_71,  s_72,  s_73,  s_74,  s_75,  s_76,
};

} // anonymous namespace ends



// If the parsing function call uses arguments, then provide an overloaded
// function.  The code below doesn't rely on parameters, so no arguments are
// required.  Furthermore, parse uses a function try block to allow us to do
// ACCEPT and ABORT from anywhere, even from within members called by actions,
// simply throwing the appropriate exceptions.

ParserBase::ParserBase()
:
    d_stackIdx__(-1),
    // $insert debuginit
    d_debug__(false),
    d_nErrors__(0),
    // $insert requiredtokens
    d_requiredTokens__(0),
    d_acceptedTokens__(d_requiredTokens__),
    d_token__(_UNDETERMINED_),
    d_nextToken__(_UNDETERMINED_)
{}


void Parser::print__()
{
// $insert print
}

void ParserBase::clearin()
{
    d_token__ = d_nextToken__ = _UNDETERMINED_;
}

void ParserBase::push__(size_t state)
{
    if (static_cast<size_t>(d_stackIdx__ + 1) == d_stateStack__.size())
    {
        size_t newSize = d_stackIdx__ + STACK_EXPANSION;
        d_stateStack__.resize(newSize);
        d_valueStack__.resize(newSize);
        // $insert LTYPEresize
        d_locationStack__.resize(newSize);
    }
    ++d_stackIdx__;
    d_stateStack__[d_stackIdx__] = d_state__ = state;
    *(d_vsp__ = &d_valueStack__[d_stackIdx__]) = d_val__;
    // $insert LTYPEpush
    *(d_lsp__ = &d_locationStack__[d_stackIdx__]) = d_loc__;
}

void ParserBase::popToken__()
{
    d_token__ = d_nextToken__;

    d_val__ = d_nextVal__;
    d_nextVal__ = STYPE__();

    d_nextToken__ = _UNDETERMINED_;
}
     
void ParserBase::pushToken__(int token)
{
    d_nextToken__ = d_token__;
    d_nextVal__ = d_val__;
    d_token__ = token;
}
     
void ParserBase::pop__(size_t count)
{
    if (d_stackIdx__ < static_cast<int>(count))
    {
        ABORT();
    }

    d_stackIdx__ -= count;
    d_state__ = d_stateStack__[d_stackIdx__];
    d_vsp__ = &d_valueStack__[d_stackIdx__];
    // $insert LTYPEpop
    d_lsp__ = &d_locationStack__[d_stackIdx__];
}

inline size_t ParserBase::top__() const
{
    return d_stateStack__[d_stackIdx__];
}

void Parser::executeAction(int production)
try
{
    if (d_token__ != _UNDETERMINED_)
        pushToken__(d_token__);     // save an already available token

                                    // save default non-nested block $$
    if (int size = s_productionInfo[production].d_size)
        d_val__ = d_vsp__[1 - size];

    switch (production)
    {
        // $insert actioncases
        
        case 8:
#line 74 "szemantikus.y"
        {
         if( szimbolumtabla.count(*d_vsp__[0].szoveg) > 0 )
         {
         std::stringstream ss;
         ss << "Ujradeklaralt valtozo: " << *d_vsp__[0].szoveg << ".\n"
         << "Korabbi deklaracio sora: " << szimbolumtabla[*d_vsp__[0].szoveg].sor << std::endl;
         error( ss.str().c_str() );
         }
         szimbolumtabla[*d_vsp__[0].szoveg] = kifejezes_leiro( d_loc__.first_line, Egesz );
         }
        break;

        case 9:
#line 86 "szemantikus.y"
        { 
         if( szimbolumtabla.count(*d_vsp__[0].szoveg) > 0 )
         {
         std::stringstream ss;
         ss << "Ujradeklaralt valtozo: " << *d_vsp__[0].szoveg << ".\n"
         << "Korabbi deklaracio sora: " << szimbolumtabla[*d_vsp__[0].szoveg].sor << std::endl;
         error( ss.str().c_str() );
         }
         szimbolumtabla[*d_vsp__[0].szoveg] = kifejezes_leiro( d_loc__.first_line, Logikai );
         }
        break;

        case 19:
#line 124 "szemantikus.y"
        {
         if( szimbolumtabla[*d_vsp__[-2].szoveg].ktip != d_vsp__[0].kif->ktip )
         {
         error( "Tipushibas ertekadas.\n" );
         }
         }
        break;

        case 22:
#line 142 "szemantikus.y"
        {
         const std::string hibauzenet = ": Az elagazas feltetele csak logikai tipusu kifejezes lehet.\n";
         if( d_vsp__[-3].kif->ktip != Logikai )
         {
         std::cerr << d_vsp__[-3].kif->sor << hibauzenet;
         exit(1);
         } 
         delete d_vsp__[-3].kif;
         }
        break;

        case 23:
#line 153 "szemantikus.y"
        {
         const std::string hibauzenet = ": Az elagazas feltetele csak logikai tipusu kifejezes lehet.\n";
         if( d_vsp__[-5].kif->ktip != Logikai )
         {
         std::cerr << d_vsp__[-5].kif->sor << hibauzenet;
         exit(1);
         } 
         delete d_vsp__[-5].kif;
         }
        break;

        case 24:
#line 166 "szemantikus.y"
        {
         const std::string hibauzenet = ": Az ciklus feltetele csak logikai tipusu kifejezes lehet.\n";
         if( d_vsp__[-2].kif->ktip != Logikai )
         {
         std::cerr << d_vsp__[-2].kif->sor << hibauzenet;
         exit(1);
         } 
         delete d_vsp__[-2].kif;
         }
        break;

        case 25:
#line 179 "szemantikus.y"
        {
         d_val__.kif = new kifejezes_leiro( d_loc__.first_line, Egesz );
         }
        break;

        case 26:
#line 184 "szemantikus.y"
        {
         d_val__.kif = new kifejezes_leiro( d_loc__.first_line, Logikai );
         }
        break;

        case 27:
#line 189 "szemantikus.y"
        {
         d_val__.kif = new kifejezes_leiro( d_loc__.first_line, Logikai );
         }
        break;

        case 28:
#line 194 "szemantikus.y"
        {
         d_val__.kif = new kifejezes_leiro( szimbolumtabla[*d_vsp__[0].szoveg].sor, szimbolumtabla[*d_vsp__[0].szoveg].ktip );
         }
        break;

        case 29:
#line 199 "szemantikus.y"
        {
         const std::string hibauzenet = ": Az osszeadas argumentuma csak egesz tipusu kifejezes lehet.\n";
         if( d_vsp__[-2].kif->ktip != Egesz )
         {
         std::cerr << d_vsp__[-2].kif->sor << hibauzenet;
         exit(1);
         }
         if( d_vsp__[0].kif->ktip != Egesz )
         {
         std::cerr << d_vsp__[0].kif->sor << hibauzenet;
         exit(1);
         }
         d_val__.kif = new kifejezes_leiro( d_vsp__[-2].kif->sor, Egesz );
         delete d_vsp__[-2].kif;
         delete d_vsp__[0].kif;
         }
        break;

        case 30:
#line 217 "szemantikus.y"
        {
         const std::string hibauzenet = ": A kivonas argumentuma csak egesz tipusu kifejezes lehet.\n";
         if( d_vsp__[-2].kif->ktip != Egesz )
         {
         std::cerr << d_vsp__[-2].kif->sor << hibauzenet;
         exit(1);
         }
         if( d_vsp__[0].kif->ktip != Egesz )
         {
         std::cerr << d_vsp__[0].kif->sor << hibauzenet;
         exit(1);
         }
         d_val__.kif = new kifejezes_leiro( d_vsp__[-2].kif->sor, Egesz );
         delete d_vsp__[-2].kif;
         delete d_vsp__[0].kif;
         }
        break;

        case 31:
#line 235 "szemantikus.y"
        { 
         const std::string hibauzenet = ": A szorzas argumentuma csak egesz tipusu kifejezes lehet.\n";
         if( d_vsp__[-2].kif->ktip != Egesz )
         {
         std::cerr << d_vsp__[-2].kif->sor << hibauzenet;
         exit(1);
         }
         if( d_vsp__[0].kif->ktip != Egesz )
         {
         std::cerr << d_vsp__[0].kif->sor << hibauzenet;
         exit(1);
         }
         d_val__.kif = new kifejezes_leiro( d_vsp__[-2].kif->sor, Egesz );
         delete d_vsp__[-2].kif;
         delete d_vsp__[0].kif;
         }
        break;

        case 32:
#line 253 "szemantikus.y"
        {
         const std::string hibauzenet = ": Az osztas argumentuma csak egesz tipusu kifejezes lehet.\n";
         if( d_vsp__[-2].kif->ktip != Egesz )
         {
         std::cerr << d_vsp__[-2].kif->sor << hibauzenet;
         exit(1);
         }
         if( d_vsp__[0].kif->ktip != Egesz )
         {
         std::cerr << d_vsp__[0].kif->sor << hibauzenet;
         exit(1);
         }
         d_val__.kif = new kifejezes_leiro( d_vsp__[-2].kif->sor, Egesz );
         delete d_vsp__[-2].kif;
         delete d_vsp__[0].kif;
         }
        break;

        case 33:
#line 271 "szemantikus.y"
        {
         const std::string hibauzenet = ": A maradekkepzes argumentuma csak egesz tipusu kifejezes lehet.\n";
         if( d_vsp__[-2].kif->ktip != Egesz )
         {
         std::cerr << d_vsp__[-2].kif->sor << hibauzenet;
         exit(1);
         }
         if( d_vsp__[0].kif->ktip != Egesz )
         {
         std::cerr << d_vsp__[0].kif->sor << hibauzenet;
         exit(1);
         }
         d_val__.kif = new kifejezes_leiro( d_vsp__[-2].kif->sor, Egesz );
         delete d_vsp__[-2].kif;
         delete d_vsp__[0].kif; 
         }
        break;

        case 34:
#line 289 "szemantikus.y"
        {
         const std::string hibauzenet = ": A kisebb argumentuma csak egesz tipusu kifejezes lehet.\n";
         if( d_vsp__[-2].kif->ktip != Egesz )
         {
         std::cerr << d_vsp__[-2].kif->sor << hibauzenet;
         exit(1);
         }
         if( d_vsp__[0].kif->ktip != Egesz )
         {
         std::cerr << d_vsp__[0].kif->sor << hibauzenet;
         exit(1);
         }
         d_val__.kif = new kifejezes_leiro( d_vsp__[-2].kif->sor, Logikai );
         delete d_vsp__[-2].kif;
         delete d_vsp__[0].kif; 
         }
        break;

        case 35:
#line 307 "szemantikus.y"
        {
         const std::string hibauzenet = ": A nagyobb argumentuma csak egesz tipusu kifejezes lehet.\n";
         if( d_vsp__[-2].kif->ktip != Egesz )
         {
         std::cerr << d_vsp__[-2].kif->sor << hibauzenet;
         exit(1);
         }
         if( d_vsp__[0].kif->ktip != Egesz )
         {
         std::cerr << d_vsp__[0].kif->sor << hibauzenet;
         exit(1);
         }
         d_val__.kif = new kifejezes_leiro( d_vsp__[-2].kif->sor, Logikai );
         delete d_vsp__[-2].kif;
         delete d_vsp__[0].kif; 
         }
        break;

        case 36:
#line 325 "szemantikus.y"
        {
         if( d_vsp__[-2].kif->ktip != d_vsp__[0].kif->ktip )
         {
         std::cerr << d_vsp__[-2].kif->sor << ": Az egyenloseg operatorral csak azonos tipusu kifejezeseket lehet osszehasonlitani.\n";
         exit(1);
         }
         d_val__.kif = new kifejezes_leiro( d_vsp__[-2].kif->sor, Logikai );
         delete d_vsp__[-2].kif;
         delete d_vsp__[0].kif;
         }
        break;

        case 37:
#line 337 "szemantikus.y"
        {
         const std::string hibauzenet = ": Az es argumentuma csak logikai tipusu kifejezes lehet.\n";
         if( d_vsp__[-2].kif->ktip != Logikai )
         {
         std::cerr << d_vsp__[-2].kif->sor << hibauzenet;
         exit(1);
         }
         if( d_vsp__[0].kif->ktip != Logikai )
         {
         std::cerr << d_vsp__[0].kif->sor << hibauzenet;
         exit(1);
         }
         d_val__.kif = new kifejezes_leiro( d_vsp__[-2].kif->sor, Logikai );
         delete d_vsp__[-2].kif;
         delete d_vsp__[0].kif; 
         }
        break;

        case 38:
#line 355 "szemantikus.y"
        {
         const std::string hibauzenet = ": A vagy argumentuma csak logikai tipusu kifejezes lehet.\n";
         if( d_vsp__[-2].kif->ktip != Logikai )
         {
         std::cerr << d_vsp__[-2].kif->sor << hibauzenet;
         exit(1);
         }
         if( d_vsp__[0].kif->ktip != Logikai )
         {
         std::cerr << d_vsp__[0].kif->sor << hibauzenet;
         exit(1);
         }
         d_val__.kif = new kifejezes_leiro( d_vsp__[-2].kif->sor, Logikai );
         delete d_vsp__[-2].kif;
         delete d_vsp__[0].kif; 
         }
        break;

        case 39:
#line 373 "szemantikus.y"
        {
         const std::string hibauzenet = ": Az nem argumentuma csak logikai tipusu kifejezes lehet.\n";
         if( d_vsp__[0].kif->ktip != Logikai )
         {
         std::cerr << d_vsp__[0].kif->sor << hibauzenet;
         exit(1);
         }
         d_val__.kif = new kifejezes_leiro( d_vsp__[0].kif->sor, Logikai );
         delete d_vsp__[0].kif; 
         }
        break;

        case 40:
#line 385 "szemantikus.y"
        {
         d_val__.kif = d_vsp__[-1].kif;
         }
        break;

    }
}
catch (std::exception const &exc)
{
    exceptionHandler__(exc);
}

inline void ParserBase::reduce__(PI__ const &pi)
{
    d_token__ = pi.d_nonTerm;
    pop__(pi.d_size);

}

// If d_token__ is _UNDETERMINED_ then if d_nextToken__ is _UNDETERMINED_ another
// token is obtained from lex(). Then d_nextToken__ is assigned to d_token__.
void Parser::nextToken()
{
    if (d_token__ != _UNDETERMINED_)        // no need for a token: got one
        return;                             // already

    if (d_nextToken__ != _UNDETERMINED_)
    {
        popToken__();                       // consume pending token
    }
    else
    {
        ++d_acceptedTokens__;               // accept another token (see
                                            // errorRecover())
        d_token__ = lex();
        if (d_token__ <= 0)
            d_token__ = _EOF_;
    }
    print();
}

// if the final transition is negative, then we should reduce by the rule
// given by its positive value. Note that the `recovery' parameter is only
// used with the --debug option
int Parser::lookup(bool recovery)
{
// $insert threading
    SR__ *sr = s_state[d_state__];          // get the appropriate state-table
    int lastIdx = sr->d_lastIdx;            // sentinel-index in the SR__ array
    
    SR__ *lastElementPtr = sr + lastIdx;
    lastElementPtr->d_token = d_token__;    // set search-token
    
    SR__ *elementPtr = sr + 1;              // start the search at s_xx[1]
    while (elementPtr->d_token != d_token__)
        ++elementPtr;
    

    if (elementPtr == lastElementPtr)   // reached the last element
    {
        if (elementPtr->d_action < 0)   // default reduction
        {
            return elementPtr->d_action;                
        }

        // No default reduction, so token not found, so error.
        throw UNEXPECTED_TOKEN__;
    }

    // not at the last element: inspect the nature of the action
    // (< 0: reduce, 0: ACCEPT, > 0: shift)

    int action = elementPtr->d_action;


    return action;
}

    // When an error has occurred, pop elements off the stack until the top
    // state has an error-item. If none is found, the default recovery
    // mode (which is to abort) is activated. 
    //
    // If EOF is encountered without being appropriate for the current state,
    // then the error recovery will fall back to the default recovery mode.
    // (i.e., parsing terminates)
void Parser::errorRecovery()
try
{
    if (d_acceptedTokens__ >= d_requiredTokens__)// only generate an error-
    {                                           // message if enough tokens 
        ++d_nErrors__;                          // were accepted. Otherwise
        error("Syntax error");                  // simply skip input

    }


    // get the error state
    while (not (s_state[top__()][0].d_type & ERR_ITEM))
    {
        pop__();
    }

    // In the error state, lookup a token allowing us to proceed.
    // Continuation may be possible following multiple reductions,
    // but eventuall a shift will be used, requiring the retrieval of
    // a terminal token. If a retrieved token doesn't match, the catch below 
    // will ensure the next token is requested in the while(true) block
    // implemented below:

    int lastToken = d_token__;                  // give the unexpected token a
                                                // chance to be processed
                                                // again.

    pushToken__(_error_);                       // specify _error_ as next token
    push__(lookup(true));                       // push the error state

    d_token__ = lastToken;                      // reactivate the unexpected
                                                // token (we're now in an
                                                // ERROR state).

    bool gotToken = true;                       // the next token is a terminal

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
            {
                gotToken = d_token__ == _UNDETERMINED_;
                nextToken();                    // obtain next token
            }
            
            int action = lookup(true);

            if (action > 0)                 // push a new state
            {
                push__(action);
                popToken__();

                if (gotToken)
                {

                    d_acceptedTokens__ = 0;
                    return;
                }
            }
            else if (action < 0)
            {
                // no actions executed on recovery but save an already 
                // available token:
                if (d_token__ != _UNDETERMINED_)
                    pushToken__(d_token__);
 
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else
                ABORT();                    // abort when accepting during
                                            // error recovery
        }
        catch (...)
        {
            if (d_token__ == _EOF_)
                ABORT();                    // saw inappropriate _EOF_
                      
            popToken__();                   // failing token now skipped
        }
    }
}
catch (ErrorRecovery__)       // This is: DEFAULT_RECOVERY_MODE
{
    ABORT();
}

    // The parsing algorithm:
    // Initially, state 0 is pushed on the stack, and d_token__ as well as
    // d_nextToken__ are initialized to _UNDETERMINED_. 
    //
    // Then, in an eternal loop:
    //
    //  1. If a state does not have REQ_TOKEN no token is assigned to
    //     d_token__. If the state has REQ_TOKEN, nextToken() is called to
    //      determine d_nextToken__ and d_token__ is set to
    //     d_nextToken__. nextToken() will not call lex() unless d_nextToken__ is 
    //     _UNDETERMINED_. 
    //
    //  2. lookup() is called: 
    //     d_token__ is stored in the final element's d_token field of the
    //     state's SR_ array. 
    //
    //  3. The current token is looked up in the state's SR_ array
    //
    //  4. Depending on the result of the lookup() function the next state is
    //     shifted on the parser's stack, a reduction by some rule is applied,
    //     or the parsing function returns ACCEPT(). When a reduction is
    //     called for, any action that may have been defined for that
    //     reduction is executed.
    //
    //  5. An error occurs if d_token__ is not found, and the state has no
    //     default reduction. Error handling was described at the top of this
    //     file.

int Parser::parse()
try 
{
    push__(0);                              // initial state
    clearin();                              // clear the tokens.

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
                nextToken();                // obtain next token


            int action = lookup(false);     // lookup d_token__ in d_state__

            if (action > 0)                 // SHIFT: push a new state
            {
                push__(action);
                popToken__();               // token processed
            }
            else if (action < 0)            // REDUCE: execute and pop.
            {
                executeAction(-action);
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else 
                ACCEPT();
        }
        catch (ErrorRecovery__)
        {
            errorRecovery();
        }
    }
}
catch (Return__ retValue)
{
    return retValue;
}



